### PR TITLE
refactor: String -> &str

### PR DESCRIPTION
**Pull request by evaporei**
### Description
There was a lot of use of the owned String type without necessity. Cases where the value is being used for comparison, or just to read &str is a better option. Unnecessary clones were removed too and .to_string() calls added as needed. Functions like ::new still use String to makes things easier.

I didn't check on `poi-radio`, but I think a few calls might need to change there.

### Checklist
- [x] Are tests up-to-date with the new changes? 
- [ ] Are docs up-to-date with the new changes? (Open PR on docs repo if necessary)

### CODE REVIEW

**Comment by axiomatic-aardvark** [comment]
thanks again 🙌🏻  seems to work just fine in POI Radio too https://github.com/graphops/poi-radio/tree/petko/str-ref-over-string

**Review by axiomatic-aardvark — APPROVED** [review]

**Comment by axiomatic-aardvark** [comment]
Clippy is being pesky

**Comment by evaporei** [comment]
@axiomatic-aardvark clippy should be happy now :slightly_smiling_face:

**Review by axiomatic-aardvark — APPROVED** [review]

**Comment by evaporei** [comment]
@axiomatic-aardvark I can't do it, I don't have access. You can merge it, it's fine haha.

**Pull request merged**
